In [1]:
import numpy as np
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1,7]])


In [2]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
mean_a = np.mean(a, 0)
mean_a

array([2. , 8.4])

In [4]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [5]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp/(a_centered.shape[0] - 1)

2.0

In [6]:
np.cov(a.T)[0, 1] == a_centered_sp/(a_centered.shape[0] - 1)

True

In [11]:
# если перемножить транспонированную матрицу на прямую и разделить на N-1, 
# получаем такую же матрицу как и с помощью np.cov(a.T)
a_centered_sp2 = (a_centered.T @ a_centered)/4
a_centered_sp2

array([[1. , 2. ],
       [2. , 4.3]])

In [10]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])