In [25]:
import numpy as np
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1,7]])


In [26]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [27]:
mean_a = np.mean(a, 0)
mean_a

array([2. , 8.4])

In [28]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [29]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp/(a_centered.shape[0] - 1)

2.0

In [30]:
np.cov(a.T)[0, 1] == a_centered_sp/(a_centered.shape[0] - 1)

True